### ISSUE TITLE
Just a guidance.

### ISSUE THREAD

**Issue by subashz** [dzolnai/ExoVisualizer#1]
Hello there, I was searching the web for the visualizer. I had done basic audio visualizer & no prior knowledge on DSP & audio processing. So, I came across your repository & began learning about it.
So, I had looked into your code and quite don't understand some of the parts. I hope you can provide some guidance on my understanding.

1.  Can't we just send `inputBuffer` as output instead of doing `        outputBuffer = this.processBuffer` in `    override fun queueInput(inputBuffer: ByteBuffer) ` method call. All the processBuffer is doing is saving from inputBuffer.

2. Also do we really need the srcBuffer. Can't we just add the short data to the src[] that we get after computing the average value from the both channels . 
`            src[i] = (summedUp / channelCount).toFloat() / Short.MAX_VALUE                                                                         
            dst[i]=0f
` I think you are using srcBuffer to make things faster by caching the data & using the same buffer for data. Is that right ? 

Also can you provide me with some learning material for understanding things like smoothing out & hamming window. Thanks for the code I learned a lot from your code. 

Also found TeeAudioProcessor that just gives the read only buffer.

**Comment by dzolnai** [comment]
Hi,

First of all, thanks for having an interest in the project. This repository is kind of a sample code to go along an article I have written about the subject, I'm not sure if you have read it?
You can check it out here: https://www.egeniq.com/blog/alternative-android-visualizer
I have also added the link to the readme of this repo now, kind of my bad of forgetting about it :)

As a disclaimer, I am also just a beginner when it comes to signal processing, so my assumptions or calculations might have errors in them. Regarding your questions:

1. I think that might work, I took this way of using the buffer from the [SonicAudioProcessor source code](https://github.com/google/ExoPlayer/blob/76962d50f1d80941d6768e4e765fa4ff010705e7/library/core/src/main/java/com/google/android/exoplayer2/audio/SonicAudioProcessor.java) of ExoPlayer. There the outputBuffer is also not used for anything else, but maybe it is indeed just extra complexity which could be avoided.

2. Yes, srcBuffer is required because that is quite a large buffer which delays the processing. The idea is that you put the latest data at the end of the buffer, and then you take from the beginning of the buffer, so it all shifts left. The large buffer is needed because if there's no delay, the processing will happen before the sound comes out of the speaker (because of AudioTrack buffer, see article), and it will look incorrect.

> Also can you provide me with some learning material for understanding things like smoothing out & hamming window. Thanks for the code I learned a lot from your code.

See the article :)

If you still have questions left, feel free to ask!

**Comment by subashz** [comment]
Thanks I was not aware that there was article on it. I had read the article & understood some of the issues, that was hard to figure out from the code. I am now trying to understand the code since I had grasped some theory behind them. Along side your code I am also trying to understand the concept in [this repo](https://github.com/Daaw/AveeOpenPlayer_1.0.34/blob/c909d8b50dcabb5d2b54dc1bfd72f9431cdd7af6/app/src/main/java/com/aveeopen/comp/Visualizer/Elements/Segment/SegmentAudioSpectrumData.java#L126): Don't know if this code follows similar concept & its hard to keep track of all the things.  Had you looked in it, previously ? This looks kinda complicated version of your code .

**Comment by dzolnai** [comment]
Sorry, but this is the first time I see that repo, and the code you linked is kind of complicated for me too, I assume it does some kind of smoothing on the FFT results.
